name:      Brock Cagann
markdown:  redcarpet
pygments:  true
permalink: /:categories/:title
# Prose settings
prose:
  siteurl: "http://brockcagann.com"
  media: "img"
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "layout"
        label: "Type"
        field:
          element: "select"
          options:
            - name: "Painting"
              value: "painting"
            - name: "Event"
              value: "event"
      - name: "categories"
        label: "Section"
        field:
          element: "select"
          options:
          - name: "Painting"
            value: "portfolio painting"
          - name: "Event"
            value: "event"
      - name: "tags"
        label: "If Painting: oil or watercolor? If Event: What type? i.e., gallery opening (all lowercase, space separated)"
        field:
          element: "text"
          value: ""
      - name: "banner"
        label: "Banner Image File Name"
        field:
          element: "text"
          value: ""
      - name: "image"
        label: "Main Image File Name"
        field:
          element: "text"
          value: ""